# Generated by Django 6.0.4 on 2026-06-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scm_containers', '0001_initial'),
        ('scm_procurement', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Supplier')),
                ('delivery_reference', models.CharField(max_length=100, verbose_name='Delivery Reference')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked'), ('in_production', 'In Production'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='planned', max_length=30, verbose_name='Status')),
                ('planned_ship_date', models.DateField(blank=True, null=True, verbose_name='Planned Ship Date')),
                ('planned_arrival_date', models.DateField(blank=True, null=True, verbose_name='Planned Arrival Date')),
                ('actual_ship_date', models.DateField(blank=True, null=True, verbose_name='Actual Ship Date')),
                ('actual_arrival_date', models.DateField(blank=True, null=True, verbose_name='Actual Arrival Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_deliveries', to='scm_procurement.purchaseorder', verbose_name='Purchase Order')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Supplier Delivery',
                'verbose_name_plural': 'Supplier Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.CharField(blank=True, max_length=255, verbose_name='Article')),
                ('delivery_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Delivery Qty')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_delivery_lines', to='scm_containers.container', verbose_name='Container')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm_supplier_deliveries.supplierdelivery', verbose_name='Delivery')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='scm_procurement.purchaseorderline', verbose_name='Purchase Order Line')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Supplier Delivery Line',
                'verbose_name_plural': 'Supplier Delivery Lines',
                'ordering': ['id'],
            },
        ),
    ]
