# Generated by Django 6.0.4 on 2026-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_procurement', '0002_purchaseorder_scm_procure_team_id_c9aacc_idx_and_more'),
        ('scm_supplier_deliveries', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplierdelivery',
            index=models.Index(fields=['team', 'status'], name='scm_supplie_team_id_cac141_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdelivery',
            index=models.Index(fields=['team', 'purchase_order'], name='scm_supplie_team_id_92bcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdelivery',
            index=models.Index(fields=['team', '-created_at'], name='scm_supplie_team_id_40efce_idx'),
        ),
    ]
