# Generated by Django 6.0.4 on 2026-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_procurement', '0002_purchaseorder_scm_procure_team_id_c9aacc_idx_and_more'),
        ('scm_supplier_deliveries', '0002_supplierdelivery_scm_supplie_team_id_cac141_idx_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierdelivery',
            constraint=models.UniqueConstraint(fields=('team', 'delivery_reference'), name='unique_supplier_delivery_ref_per_team'),
        ),
    ]
