# Generated by Django 6.0.4 on 2026-05-30 06:06

import apps.scm.containers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('iso_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ISO code')),
                ('category', models.CharField(choices=[('GP', 'General Purpose'), ('RF', 'Reefer'), ('OT', 'Open Top'), ('FR', 'Flat Rack'), ('PL', 'Platform'), ('TK', 'Tank'), ('BK', 'Bulk'), ('VH', 'Vehicle'), ('HH', 'High & Heavy')], max_length=10, verbose_name='category')),
                ('length_ft', models.PositiveSmallIntegerField(verbose_name='length (ft)')),
                ('high_cube', models.BooleanField(default=False, verbose_name='high cube')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.scm.containers.models.equipment_type_image_path, verbose_name='image')),
                ('std_external_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='std external length (mm)')),
                ('std_external_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='std external width (mm)')),
                ('std_external_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='std external height (mm)')),
                ('std_tare_weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='std tare weight (kg)')),
                ('std_max_payload', models.PositiveIntegerField(blank=True, null=True, verbose_name='std max payload (kg)')),
                ('std_cubic_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='std cubic capacity (m³)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ['length_ft', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_code', models.CharField(max_length=3, verbose_name='owner code')),
                ('category_id', models.CharField(choices=[('U', 'Freight Container (U)'), ('J', 'Detachable Freight Container Unit (J)'), ('Z', 'Trailer and Chassis (Z)')], default='U', max_length=1, verbose_name='category identifier')),
                ('serial_number', models.CharField(max_length=6, verbose_name='serial number')),
                ('check_digit', models.PositiveSmallIntegerField(verbose_name='check digit')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('REPAIR', 'Under Repair'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=10, verbose_name='condition')),
                ('color_code', models.CharField(blank=True, max_length=50, verbose_name='color code')),
                ('color_system', models.CharField(choices=[('RAL', 'RAL'), ('NCS', 'NCS'), ('PANTONE', 'Pantone'), ('CUSTOM', 'Custom'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10, verbose_name='color system')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='manufacture date')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='manufacturer')),
                ('manufacturer_id', models.CharField(blank=True, max_length=100, verbose_name='manufacturer ID')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='current location')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='scm_containers.equipmenttype', verbose_name='equipment type')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'owner_code', 'category_id', 'serial_number'], name='scm_contain_team_id_eee814_idx'), models.Index(fields=['team', 'status'], name='scm_contain_team_id_af8ae9_idx'), models.Index(fields=['team', 'condition'], name='scm_contain_team_id_250507_idx'), models.Index(fields=['team', 'equipment_type'], name='scm_contain_team_id_1a3cd4_idx'), models.Index(fields=['team', 'current_location'], name='scm_contain_team_id_c87ec6_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'owner_code', 'category_id', 'serial_number'), name='unique_container_per_team')],
            },
        ),
    ]
