# Generated by Django 6.0.4 on 2026-06-02 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0001_initial'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_number', models.CharField(help_text='Full ISO 6346 container number, e.g. MCUU1234561', max_length=11, verbose_name='container number')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('detected', 'Detected'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='status')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='carrier')),
                ('detected_at', models.DateTimeField(blank=True, null=True, verbose_name='detected at')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='last checked at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_entries', to='scm_containers.container', verbose_name='container')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_containers', to='scm_shipments.shipment', verbose_name='shipment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Planned Container',
                'verbose_name_plural': 'Planned Containers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'status'], name='scm_contain_team_id_3b0e2d_idx'), models.Index(fields=['team', 'container_number'], name='scm_contain_team_id_fcfff6_idx'), models.Index(fields=['last_checked_at'], name='scm_contain_last_ch_b05db6_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'container_number'), name='unique_planned_container_per_team')],
            },
        ),
    ]
