# Generated by Django 6.0.4 on 2026-06-14 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0002_add_planned_container'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('scm_supplier_deliveries', '0003_supplierdelivery_unique_supplier_delivery_ref_per_team'),
        ('scm_tracking', '0002_add_eta_history'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier_warehouse', 'Supplier Warehouse'), ('port', 'Port'), ('vessel', 'Vessel'), ('depot', 'Depot'), ('customer', 'Customer'), ('unknown', 'Unknown')], default='unknown', max_length=30, verbose_name='location type')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='external reference')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='owner name')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Container Location',
                'verbose_name_plural': 'Container Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('created', 'Created'), ('position_update', 'Position Update'), ('loaded_on_vessel', 'Loaded on Vessel'), ('discharged_at_port', 'Discharged at Port'), ('arrived_at_depot', 'Arrived at Depot'), ('departed_depot', 'Departed Depot'), ('manual_adjustment', 'Manual Adjustment'), ('unknown', 'Unknown')], default='unknown', max_length=30, verbose_name='movement type')),
                ('occurred_at', models.DateTimeField(verbose_name='occurred at')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('tracking_event', 'Tracking Event'), ('shipment_update', 'Shipment Update'), ('supplier_delivery', 'Supplier Delivery'), ('import', 'Import'), ('api', 'API')], default='manual', max_length=30, verbose_name='source')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Container Movement',
                'verbose_name_plural': 'Container Movements',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='container',
            new_name='scm_contain_team_id_f25638_idx',
            old_name='scm_contain_team_id_c87ec6_idx',
        ),
        migrations.AddField(
            model_name='container',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last location update'),
        ),
        migrations.AddField(
            model_name='container',
            name='location_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('tracking_event', 'Tracking Event'), ('shipment_update', 'Shipment Update'), ('supplier_delivery', 'Supplier Delivery'), ('import', 'Import'), ('api', 'API')], max_length=30, verbose_name='location source'),
        ),
        migrations.AddField(
            model_name='container',
            name='location_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='location (text)'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='container',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='scm_containers.containerlocation', verbose_name='current location'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['team', 'last_location_update'], name='scm_contain_team_id_24a884_idx'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='scm_containers.container', verbose_name='container'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='scm_containers.containerlocation', verbose_name='from location'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='related_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_movements', to='scm_shipments.shipment', verbose_name='related shipment'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='related_supplier_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_movements', to='scm_supplier_deliveries.supplierdelivery', verbose_name='related supplier delivery'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='related_tracking_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_movements', to='scm_tracking.trackingevent', verbose_name='related tracking event'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='scm_containers.containerlocation', verbose_name='to location'),
        ),
        migrations.AddIndex(
            model_name='containerlocation',
            index=models.Index(fields=['team', 'location_type'], name='scm_contain_team_id_9897b5_idx'),
        ),
        migrations.AddIndex(
            model_name='containerlocation',
            index=models.Index(fields=['team', 'is_active'], name='scm_contain_team_id_4ad4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='containermovement',
            index=models.Index(fields=['team', 'container'], name='scm_contain_team_id_e4af0d_idx'),
        ),
        migrations.AddIndex(
            model_name='containermovement',
            index=models.Index(fields=['team', 'occurred_at'], name='scm_contain_team_id_d231c2_idx'),
        ),
    ]
