# Generated by Django 6.0.4 on 2026-07-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0003_containerlocation_containermovement_and_more'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedcontainer',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='discovery attempts'),
        ),
        migrations.AddField(
            model_name='plannedcontainer',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Stop looking for this container number after this time.', null=True, verbose_name='expires at'),
        ),
        migrations.AddField(
            model_name='plannedcontainer',
            name='last_error_message',
            field=models.TextField(blank=True, verbose_name='last error message'),
        ),
        migrations.AddField(
            model_name='plannedcontainer',
            name='last_result',
            field=models.CharField(choices=[('pending', 'Not checked yet'), ('not_found', 'Not known at carrier yet'), ('detected', 'Detected'), ('skipped', 'Skipped — carrier not available'), ('error', 'Error')], default='pending', max_length=20, verbose_name='last result'),
        ),
        migrations.AddField(
            model_name='plannedcontainer',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Give up after this many attempts. Falls back to the team/global default.', null=True, verbose_name='max attempts'),
        ),
        migrations.AddField(
            model_name='plannedcontainer',
            name='next_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next check at'),
        ),
        migrations.AlterField(
            model_name='plannedcontainer',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('detected', 'Detected'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='planned', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='plannedcontainer',
            index=models.Index(fields=['status', 'next_check_at'], name='scm_contain_status_1edfb4_idx'),
        ),
    ]
