# Generated by Django 6.0.4 on 2026-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0004_plannedcontainer_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='category_id',
            field=models.CharField(choices=[('U', 'Freight Container (U)'), ('A', 'Freight Container (A)'), ('J', 'Detachable Freight Container Unit (J)'), ('Z', 'Trailer and Chassis (Z)')], default='U', max_length=1, verbose_name='category identifier'),
        ),
    ]
