# Generated by Django 6.0.4 on 2026-09-05 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0005_alter_container_category_id'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text='A TrackingProvider code, or one of the reserved sources: unlocode, internal.', max_length=50, verbose_name='source')),
                ('external_code', models.CharField(blank=True, help_text='The identifier this source uses for the place, if it has one.', max_length=100, verbose_name='external code')),
                ('external_name', models.CharField(blank=True, help_text='The place name this source reports, verbatim.', max_length=200, verbose_name='external name')),
                ('normalized_name', models.CharField(blank=True, editable=False, help_text='Derived from the external name on save, for matching. Not edited directly.', max_length=200, verbose_name='normalised name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Anything else this source published about the place, kept verbatim.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'Location Alias',
                'verbose_name_plural': 'Location Aliases',
                'ordering': ['source', 'external_name', 'external_code'],
            },
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. SE. Kept apart from the free-text country name.', max_length=2, verbose_name='country code'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='normalized_name',
            field=models.CharField(blank=True, editable=False, help_text='Derived from the name on save, for matching. Not edited directly.', max_length=200, verbose_name='normalised name'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='parent_location',
            field=models.ForeignKey(blank=True, help_text='The larger place this one sits inside, e.g. the port a terminal belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='scm_containers.containerlocation', verbose_name='parent location'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA name, e.g. Europe/Stockholm.', max_length=64, verbose_name='timezone'),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='unlocode',
            field=models.CharField(blank=True, help_text='Stored canonically, e.g. SEGOT. Several locations may share one code.', max_length=5, verbose_name='UN/LOCODE'),
        ),
        migrations.AlterField(
            model_name='containerlocation',
            name='location_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier_warehouse', 'Supplier Warehouse'), ('port', 'Port'), ('vessel', 'Vessel'), ('depot', 'Depot'), ('customer', 'Customer'), ('terminal', 'Terminal'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=30, verbose_name='location type'),
        ),
        migrations.AddIndex(
            model_name='containerlocation',
            index=models.Index(fields=['team', 'unlocode'], name='scm_contain_team_id_96dfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='containerlocation',
            index=models.Index(fields=['team', 'normalized_name'], name='scm_contain_team_id_cadd65_idx'),
        ),
        migrations.AddIndex(
            model_name='containerlocation',
            index=models.Index(fields=['team', 'parent_location'], name='scm_contain_team_id_4da60a_idx'),
        ),
        migrations.AddField(
            model_name='locationalias',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='scm_containers.containerlocation', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='locationalias',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddIndex(
            model_name='locationalias',
            index=models.Index(fields=['team', 'source', 'normalized_name'], name='scm_contain_team_id_819305_idx'),
        ),
        migrations.AddIndex(
            model_name='locationalias',
            index=models.Index(fields=['team', 'source', 'external_code'], name='scm_contain_team_id_20ab53_idx'),
        ),
        migrations.AddIndex(
            model_name='locationalias',
            index=models.Index(fields=['team', 'location'], name='scm_contain_team_id_26c6ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationalias',
            constraint=models.UniqueConstraint(condition=models.Q(('external_code__gt', '')), fields=('team', 'source', 'external_code'), name='unique_location_alias_code_per_source'),
        ),
        migrations.AddConstraint(
            model_name='locationalias',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_name__gt', '')), fields=('team', 'source', 'normalized_name'), name='unique_location_alias_name_per_source'),
        ),
    ]
