# Generated by Django 6.0.4 on 2026-09-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0007_backfill_location_normalized_names'),
        ('scm_shipments', '0003_shipment_destination_location_and_more'),
        ('scm_supplier_deliveries', '0003_supplierdelivery_unique_supplier_delivery_ref_per_team'),
        ('scm_tracking', '0010_trackingevent_location_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermovement',
            name='affects_current_state',
            field=models.BooleanField(default=True, help_text='Whether this movement is a claim about where the container is, or history only.', verbose_name='affects current state'),
        ),
        migrations.AddField(
            model_name='containermovement',
            name='gate_name',
            field=models.CharField(blank=True, help_text='The gate the container passed through, e.g. John Evans. Not a location.', max_length=100, verbose_name='gate'),
        ),
        migrations.AlterField(
            model_name='container',
            name='location_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('depot', 'Depot'), ('tracking_event', 'Tracking Event'), ('shipment_update', 'Shipment Update'), ('supplier_delivery', 'Supplier Delivery'), ('import', 'Import'), ('api', 'API')], max_length=30, verbose_name='location source'),
        ),
        migrations.AlterField(
            model_name='containermovement',
            name='movement_type',
            field=models.CharField(choices=[('gate_in', 'Gate In'), ('gate_out', 'Gate Out'), ('received', 'Received'), ('transfer', 'Transfer'), ('created', 'Created'), ('position_update', 'Position Update'), ('loaded_on_vessel', 'Loaded on Vessel'), ('discharged_at_port', 'Discharged at Port'), ('arrived_at_depot', 'Arrived at Depot'), ('departed_depot', 'Departed Depot'), ('manual_adjustment', 'Manual Adjustment'), ('unknown', 'Unknown')], default='unknown', max_length=30, verbose_name='movement type'),
        ),
        migrations.AlterField(
            model_name='containermovement',
            name='related_tracking_event',
            field=models.ForeignKey(blank=True, help_text='The carrier event this movement was interpreted from, when it came from one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_movements', to='scm_tracking.trackingevent', verbose_name='related tracking event'),
        ),
        migrations.AlterField(
            model_name='containermovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('depot', 'Depot'), ('tracking_event', 'Tracking Event'), ('shipment_update', 'Shipment Update'), ('supplier_delivery', 'Supplier Delivery'), ('import', 'Import'), ('api', 'API')], default='manual', max_length=30, verbose_name='source'),
        ),
        migrations.AddIndex(
            model_name='containermovement',
            index=models.Index(fields=['team', 'container', '-occurred_at'], name='scm_contain_team_id_183efe_idx'),
        ),
        migrations.AddIndex(
            model_name='containermovement',
            index=models.Index(fields=['team', 'to_location', 'movement_type'], name='scm_contain_team_id_15e1ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='containermovement',
            constraint=models.UniqueConstraint(condition=models.Q(('related_tracking_event__isnull', False)), fields=('related_tracking_event',), name='unique_movement_per_tracking_event'),
        ),
    ]
