# Generated by Django 6.0.4 on 2026-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0011_container_condition_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='tracking_provider_override',
            field=models.CharField(blank=True, help_text="Provider code to track this container through. Blank uses the team's standard routing.", max_length=50, verbose_name='tracking via'),
        ),
    ]
