# Generated by Django 6.0.4 on 2026-05-30 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scm_containers', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(blank=True, max_length=100, verbose_name='shipment number')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='customer name')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='carrier')),
                ('carrier_booking_reference', models.CharField(blank=True, max_length=100, verbose_name='carrier booking reference')),
                ('bill_of_lading_number', models.CharField(blank=True, max_length=100, verbose_name='bill of lading number')),
                ('origin_port', models.CharField(blank=True, max_length=200, verbose_name='origin port')),
                ('destination_port', models.CharField(blank=True, max_length=200, verbose_name='destination port')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='estimated departure')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='estimated arrival')),
                ('actual_departure_at', models.DateTimeField(blank=True, null=True, verbose_name='actual departure')),
                ('actual_arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='actual arrival')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('tracking_status', models.CharField(blank=True, max_length=200, verbose_name='tracking status')),
                ('last_tracking_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='last tracking sync')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='sequence')),
                ('seal_number', models.CharField(blank=True, max_length=100, verbose_name='seal number')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='gross weight (kg)')),
                ('loaded_at', models.DateTimeField(blank=True, null=True, verbose_name='loaded at')),
                ('discharged_at', models.DateTimeField(blank=True, null=True, verbose_name='discharged at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_containers', to='scm_containers.container', verbose_name='container')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_containers', to='scm_shipments.shipment', verbose_name='shipment')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('CONTAINER_ADDED', 'Container Added'), ('CONTAINER_REMOVED', 'Container Removed'), ('ETA_UPDATED', 'ETA Updated'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('TRACKING_UPDATED', 'Tracking Updated'), ('NOTE_ADDED', 'Note Added')], max_length=50, verbose_name='event type')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='occurred at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipment_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scm_shipments.shipment', verbose_name='shipment')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['team', 'status'], name='scm_shipmen_team_id_93212a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['team', 'eta'], name='scm_shipmen_team_id_f1a146_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['team', 'etd'], name='scm_shipmen_team_id_05164b_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('shipment_number__gt', '')), fields=('team', 'shipment_number'), name='unique_team_shipment_number'),
        ),
        migrations.AddIndex(
            model_name='shipmentcontainer',
            index=models.Index(fields=['shipment', 'sequence'], name='scm_shipmen_shipmen_1353f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentcontainer',
            constraint=models.UniqueConstraint(fields=('shipment', 'container'), name='unique_container_per_shipment'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', '-occurred_at'], name='scm_shipmen_shipmen_ad6866_idx'),
        ),
    ]
