# Generated by Django 6.0.4 on 2026-06-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='eta_confidence',
            field=models.CharField(blank=True, max_length=20, verbose_name='ETA confidence'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='eta_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA last updated'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='eta_source',
            field=models.CharField(blank=True, max_length=50, verbose_name='ETA source'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='original_eta',
            field=models.DateField(blank=True, null=True, verbose_name='original ETA'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('EXCEPTION', 'Exception')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('CONTAINER_ADDED', 'Container Added'), ('CONTAINER_REMOVED', 'Container Removed'), ('ETA_UPDATED', 'ETA Updated'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('TRACKING_UPDATED', 'Tracking Updated'), ('SUPPLIER_DELIVERY_LINKED', 'Supplier Delivery Linked'), ('EXCEPTION', 'Exception'), ('NOTE_ADDED', 'Note Added')], max_length=50, verbose_name='event type'),
        ),
    ]
