# Generated by Django 6.0.4 on 2026-09-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0006_locationalias_containerlocation_country_code_and_more'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='The canonical location this shipment is bound for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shipments', to='scm_containers.containerlocation', verbose_name='destination location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_location',
            field=models.ForeignKey(blank=True, help_text='The canonical location this shipment departs from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipments', to='scm_containers.containerlocation', verbose_name='origin location'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['team', 'destination_location', 'eta'], name='scm_shipmen_team_id_2fb95d_idx'),
        ),
    ]
