# Generated by Django 6.0.4 on 2026-05-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scm_containers', '0001_initial'),
        ('scm_shipments', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('provider_type', models.CharField(choices=[('api', 'API'), ('scraping', 'Scraping'), ('webhook', 'Webhook'), ('manual', 'Manual')], default='api', max_length=20, verbose_name='provider type')),
                ('base_url', models.URLField(blank=True, verbose_name='base URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_reference', models.CharField(max_length=200, verbose_name='tracking reference')),
                ('reference_type', models.CharField(choices=[('container_number', 'Container Number'), ('booking_number', 'Booking Number'), ('bill_of_lading', 'Bill of Lading'), ('shipment_reference', 'Shipment Reference'), ('manual', 'Manual')], default='container_number', max_length=30, verbose_name='reference type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
                ('next_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='next sync at')),
                ('last_error_message', models.TextField(blank=True, verbose_name='last error message')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='last error at')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='consecutive failures')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_subscriptions', to='scm_containers.container', verbose_name='container')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='scm_tracking.trackingprovider', verbose_name='provider')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_subscriptions', to='scm_shipments.shipment', verbose_name='shipment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingRawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_type', models.CharField(choices=[('api_response', 'API Response'), ('webhook', 'Webhook'), ('scrape_result', 'Scrape Result'), ('manual_import', 'Manual Import'), ('error_response', 'Error Response')], default='api_response', max_length=20, verbose_name='payload type')),
                ('payload_json', models.JSONField(default=dict, verbose_name='payload JSON')),
                ('payload_hash', models.CharField(blank=True, max_length=64, verbose_name='payload hash')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='received at')),
                ('parsed_successfully', models.BooleanField(default=False, verbose_name='parsed successfully')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_payloads', to='scm_tracking.trackingprovider', verbose_name='provider')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_payloads', to='scm_tracking.trackingsubscription', verbose_name='subscription')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('empty_released', 'Empty Released'), ('gate_in', 'Gate In'), ('loaded_on_vessel', 'Loaded on Vessel'), ('vessel_departed', 'Vessel Departed'), ('transshipment_arrived', 'Transshipment Arrived'), ('transshipment_departed', 'Transshipment Departed'), ('vessel_arrived', 'Vessel Arrived'), ('discharged', 'Discharged'), ('gate_out', 'Gate Out'), ('delivered', 'Delivered'), ('customs_hold', 'Customs Hold'), ('delay', 'Delay'), ('eta_updated', 'ETA Updated'), ('unknown', 'Unknown')], default='unknown', max_length=40, verbose_name='event type')),
                ('event_code', models.CharField(blank=True, max_length=100, verbose_name='event code')),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='location name')),
                ('location_unlocode', models.CharField(blank=True, max_length=10, verbose_name='UN/LOCODE')),
                ('event_datetime', models.DateTimeField(blank=True, null=True, verbose_name='event datetime')),
                ('event_timezone', models.CharField(blank=True, max_length=50, verbose_name='event timezone')),
                ('source_event_id', models.CharField(blank=True, max_length=200, verbose_name='source event ID')),
                ('confidence', models.PositiveSmallIntegerField(default=100, verbose_name='confidence')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='raw data')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='scm_containers.container', verbose_name='container')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='scm_shipments.shipment', verbose_name='shipment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='scm_tracking.trackingprovider', verbose_name='provider')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scm_tracking.trackingsubscription', verbose_name='subscription')),
            ],
            options={
                'ordering': ['-event_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('events_created', models.PositiveIntegerField(default=0, verbose_name='events created')),
                ('events_updated', models.PositiveIntegerField(default=0, verbose_name='events updated')),
                ('raw_payloads_created', models.PositiveIntegerField(default=0, verbose_name='raw payloads created')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='scm_tracking.trackingprovider', verbose_name='provider')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='scm_tracking.trackingsubscription', verbose_name='subscription')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['team', 'status'], name='scm_trackin_team_id_6a19cb_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['team', 'provider'], name='scm_trackin_team_id_b540be_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['team', 'shipment'], name='scm_trackin_team_id_e444fd_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['team', 'container'], name='scm_trackin_team_id_15e84d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['next_sync_at'], name='scm_trackin_next_sy_1442c4_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingrawpayload',
            index=models.Index(fields=['team', 'provider'], name='scm_trackin_team_id_362aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingrawpayload',
            index=models.Index(fields=['team', 'subscription'], name='scm_trackin_team_id_fec7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingrawpayload',
            index=models.Index(fields=['received_at'], name='scm_trackin_receive_fad8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['team', 'shipment'], name='scm_trackin_team_id_5c94ed_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['team', 'container'], name='scm_trackin_team_id_a1e03e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['team', 'provider'], name='scm_trackin_team_id_fef297_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event_datetime'], name='scm_trackin_event_d_fecae8_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['source_event_id'], name='scm_trackin_source__1aa703_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event_id__gt', '')), fields=('team', 'provider', 'source_event_id'), name='unique_tracking_event_source_id'),
        ),
        migrations.AddIndex(
            model_name='trackingsyncrun',
            index=models.Index(fields=['team', 'subscription'], name='scm_trackin_team_id_3526f6_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsyncrun',
            index=models.Index(fields=['team', 'provider'], name='scm_trackin_team_id_e0e809_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsyncrun',
            index=models.Index(fields=['started_at'], name='scm_trackin_started_ea3a9a_idx'),
        ),
    ]
