# Generated by Django 6.0.4 on 2026-06-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0001_initial'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('scm_tracking', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_eta', models.DateField(blank=True, null=True, verbose_name='previous ETA')),
                ('new_eta', models.DateField(blank=True, null=True, verbose_name='new ETA')),
                ('changed_at', models.DateTimeField(verbose_name='changed at')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='source')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eta_history', to='scm_containers.container', verbose_name='container')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_history', to='scm_shipments.shipment', verbose_name='shipment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'ETA History',
                'verbose_name_plural': 'ETA History',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['team', 'shipment'], name='scm_trackin_team_id_35f430_idx'), models.Index(fields=['team', 'container'], name='scm_trackin_team_id_4c40a4_idx'), models.Index(fields=['changed_at'], name='scm_trackin_changed_aa6860_idx')],
            },
        ),
    ]
