# Generated by Django 6.0.4 on 2026-07-25 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0003_containerlocation_containermovement_and_more'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('scm_tracking', '0002_add_eta_history'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackingevent',
            name='unique_tracking_event_source_id',
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='carrier_description',
            field=models.TextField(blank=True, verbose_name='carrier description'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='carrier_event_type',
            field=models.CharField(blank=True, max_length=60, verbose_name='carrier event type'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='equipment_reference',
            field=models.CharField(blank=True, max_length=20, verbose_name='equipment reference'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='event_fingerprint',
            field=models.CharField(blank=True, help_text='Stable hash used to recognise the same carrier event across syncs.', max_length=64, verbose_name='event fingerprint'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='event_time_type',
            field=models.CharField(choices=[('actual', 'Actual'), ('estimated', 'Estimated'), ('planned', 'Planned'), ('requested', 'Requested'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='event time type'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='raw_payload',
            field=models.ForeignKey(blank=True, help_text='The stored carrier response this event was parsed from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scm_tracking.trackingrawpayload', verbose_name='raw payload'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received at'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('vessel', 'Vessel'), ('rail', 'Rail'), ('truck', 'Truck'), ('barge', 'Barge'), ('air', 'Air'), ('other', 'Other')], max_length=20, verbose_name='transport mode'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='vessel_imo',
            field=models.CharField(blank=True, max_length=20, verbose_name='vessel IMO'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='vessel name'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='voyage_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='voyage number'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['team', 'container', 'event_time_type'], name='scm_trackin_team_id_8777bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_fingerprint__gt', '')), fields=('team', 'provider', 'event_fingerprint'), name='unique_tracking_event_fingerprint'),
        ),
    ]
