# Generated by Django 6.0.4 on 2026-07-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0003_containerlocation_containermovement_and_more'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('scm_tracking', '0004_backfill_tracking_event_fingerprints'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsubscription',
            name='last_event_at',
            field=models.DateTimeField(blank=True, help_text='When this subscription last produced at least one carrier event.', null=True, verbose_name='last event received at'),
        ),
        migrations.AddField(
            model_name='trackingsubscription',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Overrides the state-based polling interval for this subscription.', null=True, verbose_name='sync interval (minutes)'),
        ),
        migrations.AddField(
            model_name='trackingsubscription',
            name='tracking_status',
            field=models.CharField(choices=[('pending', 'Pending first sync'), ('no_data', 'No data at carrier yet'), ('tracking', 'Tracking'), ('not_configured', 'Carrier not configured'), ('error', 'Error')], default='pending', max_length=20, verbose_name='tracking status'),
        ),
        migrations.AddField(
            model_name='trackingsyncrun',
            name='error_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('not_implemented', 'Adapter not implemented'), ('not_configured', 'Integration not configured'), ('already_running', 'Sync already running'), ('unsupported_reference', 'Unsupported reference'), ('authentication', 'Authentication failed'), ('rate_limit', 'Rate limited'), ('timeout', 'Timeout or network error'), ('server_error', 'Carrier server error'), ('invalid_response', 'Invalid or unparseable response'), ('parse_error', 'Parser error'), ('unexpected', 'Unexpected error')], default='', max_length=30, verbose_name='error type'),
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['team', 'tracking_status'], name='scm_trackin_team_id_a9fb85_idx'),
        ),
    ]
