# Generated by Django 6.0.4 on 2026-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_tracking', '0005_trackingsubscription_last_event_at_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingrawpayload',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the payload body was dropped by retention. Hash and metadata are kept.', null=True, verbose_name='archived at'),
        ),
        migrations.AddField(
            model_name='trackingrawpayload',
            name='payload_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the original payload, retained after the body is archived away.', null=True, verbose_name='payload size (bytes)'),
        ),
        migrations.AddIndex(
            model_name='trackingrawpayload',
            index=models.Index(fields=['archived_at', 'received_at'], name='scm_trackin_archive_a40a82_idx'),
        ),
    ]
