# Generated by Django 6.0.4 on 2026-07-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0004_plannedcontainer_attempts_and_more'),
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('scm_tracking', '0006_trackingrawpayload_archived_at_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etahistory',
            name='delta_minutes',
            field=models.IntegerField(blank=True, help_text='Positive when the ETA moved later (a delay), negative when it moved earlier.', null=True, verbose_name='delta (minutes)'),
        ),
        migrations.AddField(
            model_name='etahistory',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='location name'),
        ),
        migrations.AddField(
            model_name='etahistory',
            name='location_unlocode',
            field=models.CharField(blank=True, max_length=10, verbose_name='UN/LOCODE'),
        ),
        migrations.AddField(
            model_name='etahistory',
            name='new_eta_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='new ETA (precise)'),
        ),
        migrations.AddField(
            model_name='etahistory',
            name='previous_eta_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous ETA (precise)'),
        ),
        migrations.AddField(
            model_name='etahistory',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When we learned about this forecast, which can lag when the carrier issued it.', null=True, verbose_name='received at'),
        ),
        migrations.AddField(
            model_name='etahistory',
            name='tracking_event',
            field=models.ForeignKey(blank=True, help_text='The carrier event this forecast came from, when it came from one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eta_changes', to='scm_tracking.trackingevent', verbose_name='tracking event'),
        ),
        migrations.AddIndex(
            model_name='etahistory',
            index=models.Index(fields=['team', 'shipment', '-changed_at'], name='scm_trackin_team_id_08eaad_idx'),
        ),
    ]
