# Generated by Django 6.0.4 on 2026-08-20 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Let an ETA forecast be recorded for a container that is not on a shipment.

    A tracked container need not be on a shipment — the ones this project tracks today
    are not — and until now that made its arrival forecast unrecordable, because
    ``shipment`` was the one required subject. ``container`` was already optional, so
    this is a single DROP NOT NULL: no data changes, no new table, and every existing
    reader filters on ``shipment``, which a NULL row simply does not match.
    """

    dependencies = [
        ('scm_shipments', '0002_shipment_eta_confidence_shipment_eta_last_updated_and_more'),
        ('scm_tracking', '0008_sync_run_not_carrier_polled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etahistory',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='The shipment this forecast is for, when the journey is on one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eta_history', to='scm_shipments.shipment', verbose_name='shipment'),
        ),
    ]
