# Generated by Django 6.0.4 on 2026-09-05 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0006_locationalias_containerlocation_country_code_and_more'),
        ('scm_shipments', '0003_shipment_destination_location_and_more'),
        ('scm_tracking', '0009_etahistory_shipment_optional'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='location',
            field=models.ForeignKey(blank=True, help_text="The canonical location this event's reported place resolved to, when it did.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='scm_containers.containerlocation', verbose_name='canonical location'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='location_resolution_method',
            field=models.CharField(blank=True, choices=[('alias', 'Explicit alias'), ('external_code', 'Provider code'), ('unlocode', 'UN/LOCODE'), ('coordinates', 'Coordinates'), ('name', 'Normalised name'), ('none', 'None')], max_length=20, verbose_name='location resolution method'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='location_resolution_status',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('ambiguous', 'Ambiguous')], max_length=20, verbose_name='location resolution status'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['team', 'location'], name='scm_trackin_team_id_50d54a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['team', 'location_resolution_status'], name='scm_trackin_team_id_2e474f_idx'),
        ),
    ]
