# Generated by Django 6.0.4 on 2026-09-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0008_containermovement_affects_current_state_and_more'),
        ('scm_shipments', '0003_shipment_destination_location_and_more'),
        ('scm_tracking', '0010_trackingevent_location_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsubscription',
            name='carrier_code',
            field=models.CharField(blank=True, help_text='The registry code of the carrier moving this container, when it is known.', max_length=50, verbose_name='carrier code'),
        ),
        migrations.AddField(
            model_name='trackingsubscription',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='carrier name'),
        ),
        migrations.AddField(
            model_name='trackingsubscription',
            name='carrier_source',
            field=models.CharField(blank=True, choices=[('manual', 'Chosen by a person'), ('shipment', 'From the shipment'), ('planned_container', 'From the planned container'), ('existing_verified_source', 'Already verified for this container'), ('traqo_lookup', 'Traqo carrier lookup'), ('direct_api', 'Direct carrier tracking events'), ('vizion_aci', 'Vizion Auto Carrier Identification')], help_text='How the carrier was established. Blank when no carrier is recorded.', max_length=30, verbose_name='carrier identified via'),
        ),
        migrations.AddField(
            model_name='trackingsubscription',
            name='provider_reference',
            field=models.CharField(blank=True, help_text="The provider's own handle for this watch — Traqo's sealine, Vizion's reference id. What a later fetch needs in order to ask the same question again.", max_length=200, verbose_name='provider reference'),
        ),
        migrations.AlterField(
            model_name='trackingsubscription',
            name='provider',
            field=models.ForeignKey(help_text="The technical provider whose API supplies this watch's data — not necessarily the carrier.", on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='scm_tracking.trackingprovider', verbose_name='provider'),
        ),
        migrations.AddIndex(
            model_name='trackingsubscription',
            index=models.Index(fields=['team', 'carrier_code'], name='scm_trackin_team_id_9fd998_idx'),
        ),
    ]
