# Generated by Django 6.0.4 on 2026-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_tracking', '0012_backfill_subscription_carrier_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsubscription',
            name='carrier_source',
            field=models.CharField(blank=True, choices=[('manual', 'Chosen by a person'), ('shipment', 'From the shipment'), ('planned_container', 'From the planned container'), ('existing_verified_source', 'Already verified for this container'), ('traqo_lookup', 'Traqo carrier lookup'), ('traqo_probe', 'Traqo container tracking data'), ('direct_api', 'Direct carrier tracking events'), ('vizion_aci', 'Vizion Auto Carrier Identification')], help_text='How the carrier was established. Blank when no carrier is recorded.', max_length=30, verbose_name='carrier identified via'),
        ),
    ]
