# Generated by Django 6.0.4 on 2026-09-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_tracking', '0013_alter_trackingsubscription_carrier_source'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_provider_code', models.CharField(default='traqo', help_text='The provider used when no direct carrier integration can answer for a container.', max_length=50, verbose_name='default tracking provider')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Tracking Settings',
                'verbose_name_plural': 'Team Tracking Settings',
                'constraints': [models.UniqueConstraint(fields=('team',), name='unique_team_tracking_settings')],
            },
        ),
    ]
