# Generated by Django 6.0.4 on 2026-09-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_tracking', '0014_teamtrackingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtrackingsettings',
            name='auto_start_tracking_for_new_containers',
            field=models.BooleanField(default=False, help_text='Start tracking a container as soon as it is created or imported. An import can override this for one run.', verbose_name='automatically start tracking for newly created containers'),
        ),
    ]
