# Generated by Django 6.0.4 on 2026-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_tracking', '0015_teamtrackingsettings_auto_start_tracking_for_new_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsyncrun',
            name='error_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('not_implemented', 'Adapter not implemented'), ('not_configured', 'Integration not configured'), ('not_carrier_polled', 'Not polled by the carrier sync'), ('provider_quota', 'Provider allowance spent for this cycle'), ('provider_billing', 'Provider account suspended for billing'), ('already_running', 'Sync already running'), ('unsupported_reference', 'Unsupported reference'), ('authentication', 'Authentication failed'), ('rate_limit', 'Rate limited'), ('timeout', 'Timeout or network error'), ('server_error', 'Carrier server error'), ('invalid_response', 'Invalid or unparseable response'), ('parse_error', 'Parser error'), ('unexpected', 'Unexpected error')], default='', max_length=30, verbose_name='error type'),
        ),
    ]
