# Generated by Django 6.0.4 on 2026-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_tracking', '0016_alter_trackingsyncrun_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtrackingsettings',
            name='stop_tracking_on_receive',
            field=models.BooleanField(default=False, help_text='Stop tracking a container once a new gate-in is recorded for it. Receiving it is recorded either way.', verbose_name='automatically stop tracking when a container is received'),
        ),
    ]
