# Generated by Django 6.0.4 on 2026-05-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('total_shipments', models.PositiveIntegerField(default=0, verbose_name='total shipments')),
                ('active_shipments', models.PositiveIntegerField(default=0, verbose_name='active shipments')),
                ('completed_shipments', models.PositiveIntegerField(default=0, verbose_name='completed shipments')),
                ('containers_in_transit', models.PositiveIntegerField(default=0, verbose_name='containers in transit')),
                ('containers_delivered', models.PositiveIntegerField(default=0, verbose_name='containers delivered')),
                ('avg_transit_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='average transit days')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['team', '-date'], name='scm_analyti_team_id_c3bdc6_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'date'), name='unique_analytics_snapshot_per_team_date')],
            },
        ),
    ]
