# Generated by Django 6.0.4 on 2026-06-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm_analytics', '0002_savedfilter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedfilter',
            new_name='scm_analyti_team_id_e72d1c_idx',
            old_name='scm_analyti_team_id_sf_idx',
        ),
    ]
