# Generated by Django 6.0.4 on 2026-06-03 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCMAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('import_started', 'Import Started'), ('import_completed', 'Import Completed'), ('import_failed', 'Import Failed'), ('shipment_created', 'Shipment Created'), ('shipment_updated', 'Shipment Updated'), ('shipment_status_changed', 'Shipment Status Changed'), ('delivery_created', 'Delivery Created'), ('delivery_updated', 'Delivery Updated'), ('delivery_status_changed', 'Delivery Status Changed'), ('container_created', 'Container Created'), ('container_updated', 'Container Updated'), ('container_linked', 'Container Linked to Shipment'), ('container_unlinked', 'Container Unlinked from Shipment'), ('container_discovered', 'Container Discovered'), ('tracking_sync_completed', 'Tracking Sync Completed'), ('tracking_sync_failed', 'Tracking Sync Failed'), ('saved_filter_created', 'Saved Filter Created'), ('saved_filter_deleted', 'Saved Filter Deleted'), ('integration_credential_updated', 'Integration Credential Updated'), ('manual_override', 'Manual Override')], max_length=60, verbose_name='action')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='object type')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='object representation')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-initiated actions (Celery tasks, scheduled jobs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'SCM Audit Log',
                'verbose_name_plural': 'SCM Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='scm_audit_l_team_id_193e18_idx'), models.Index(fields=['team', 'action'], name='scm_audit_l_team_id_adaf3a_idx'), models.Index(fields=['team', 'object_type', 'object_id'], name='scm_audit_l_team_id_2117fd_idx')],
            },
        ),
    ]
