# Generated by Django 6.0.4 on 2026-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scmauditlog',
            name='action',
            field=models.CharField(choices=[('import_started', 'Import Started'), ('import_completed', 'Import Completed'), ('import_failed', 'Import Failed'), ('shipment_created', 'Shipment Created'), ('shipment_updated', 'Shipment Updated'), ('shipment_status_changed', 'Shipment Status Changed'), ('delivery_created', 'Delivery Created'), ('delivery_updated', 'Delivery Updated'), ('delivery_status_changed', 'Delivery Status Changed'), ('container_created', 'Container Created'), ('container_updated', 'Container Updated'), ('container_linked', 'Container Linked to Shipment'), ('container_unlinked', 'Container Unlinked from Shipment'), ('container_discovered', 'Container Discovered'), ('tracking_sync_completed', 'Tracking Sync Completed'), ('tracking_sync_failed', 'Tracking Sync Failed'), ('tracking_started', 'Tracking Started'), ('tracking_stopped', 'Tracking Stopped'), ('saved_filter_created', 'Saved Filter Created'), ('saved_filter_deleted', 'Saved Filter Deleted'), ('integration_credential_updated', 'Integration Credential Updated'), ('manual_override', 'Manual Override')], max_length=60, verbose_name='action'),
        ),
    ]
