# Generated by Django 6.0.4 on 2026-06-01 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_number', models.CharField(max_length=20, verbose_name='Container Number')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('detected', 'Detected'), ('retired', 'Retired')], default='planned', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Container Pool Entry',
                'verbose_name_plural': 'Container Pool Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerDiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_number', models.CharField(max_length=20, verbose_name='Container Number')),
                ('carrier_code', models.CharField(blank=True, max_length=50, verbose_name='Carrier Code')),
                ('carrier_name', models.CharField(blank=True, max_length=200, verbose_name='Carrier Name')),
                ('event_type', models.CharField(choices=[('search_started', 'Search Started'), ('container_detected', 'Container Detected'), ('search_failed', 'Search Failed')], max_length=30, verbose_name='Event Type')),
                ('detected_at', models.DateTimeField(blank=True, null=True, verbose_name='Detected At')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('container_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_events', to='scm_container_discovery.containerpool', verbose_name='Container Pool Entry')),
            ],
            options={
                'verbose_name': 'Container Discovery Event',
                'verbose_name_plural': 'Container Discovery Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='containerpool',
            constraint=models.UniqueConstraint(fields=('team', 'container_number'), name='unique_team_container_number'),
        ),
        migrations.AddIndex(
            model_name='containerdiscoveryevent',
            index=models.Index(fields=['team', 'container_number'], name='scm_contain_team_id_887ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='containerdiscoveryevent',
            index=models.Index(fields=['team', 'event_type'], name='scm_contain_team_id_463bc0_idx'),
        ),
    ]
