# Generated by Django 6.0.4 on 2026-05-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('provider_code', models.CharField(max_length=100, verbose_name='provider code')),
                ('provider_family', models.CharField(choices=[('carrier', 'Carrier'), ('business_system', 'Business System'), ('finance', 'Finance'), ('other', 'Other')], default='carrier', max_length=20, verbose_name='provider family')),
                ('api_style', models.CharField(choices=[('dcsa', 'DCSA'), ('proprietary', 'Proprietary'), ('edi', 'EDI'), ('aggregator', 'Aggregator'), ('portal', 'Portal'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='API style')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending')], default='inactive', max_length=20, verbose_name='status')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='config')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='last tested at')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='last success at')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='last error at')),
                ('last_error_message', models.TextField(blank=True, verbose_name='last error message')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'provider_code')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('certificate', 'Certificate'), ('custom', 'Custom')], max_length=20, verbose_name='auth type')),
                ('encrypted_data', models.TextField(blank=True, verbose_name='encrypted data')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True, verbose_name='last refreshed at')),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='scm_integrations.integration', verbose_name='integration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=100, verbose_name='provider code')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP method')),
                ('endpoint', models.CharField(max_length=500, verbose_name='endpoint')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='status code')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('request_id', models.CharField(blank=True, max_length=200, verbose_name='request ID')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='scm_integrations.integration', verbose_name='integration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'provider_code'], name='scm_integra_team_id_44fd3c_idx'), models.Index(fields=['team', 'integration'], name='scm_integra_team_id_b147b9_idx'), models.Index(fields=['created_at'], name='scm_integra_created_63c7c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=100, verbose_name='provider code')),
                ('event_type', models.CharField(blank=True, max_length=200, verbose_name='event type')),
                ('external_event_id', models.CharField(blank=True, max_length=200, verbose_name='external event ID')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='headers')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='scm_integrations.integration', verbose_name='integration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'provider_code'], name='scm_integra_team_id_2785db_idx'), models.Index(fields=['status'], name='scm_integra_status_ea7813_idx'), models.Index(fields=['created_at'], name='scm_integra_created_81c66f_idx')],
            },
        ),
    ]
