# Generated by Django 6.0.4 on 2026-07-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_integrations', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('purchase_orders', 'Purchase orders')], default='purchase_orders', max_length=40, verbose_name='resource type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partially_completed', 'Partially completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('retry', 'Retry')], default='scheduled', max_length=20, verbose_name='trigger type')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='correlation ID')),
                ('watermark_from', models.DateTimeField(blank=True, null=True, verbose_name='watermark from')),
                ('watermark_to', models.DateTimeField(blank=True, null=True, verbose_name='watermark to')),
                ('records_fetched', models.PositiveIntegerField(default=0, verbose_name='records fetched')),
                ('records_created', models.PositiveIntegerField(default=0, verbose_name='records created')),
                ('records_updated', models.PositiveIntegerField(default=0, verbose_name='records updated')),
                ('records_unchanged', models.PositiveIntegerField(default=0, verbose_name='records unchanged')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='records failed')),
                ('error_summary', models.TextField(blank=True, verbose_name='error summary')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='scm_integrations.integration', verbose_name='integration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'integration'], name='scm_integra_team_id_33cfaf_idx'), models.Index(fields=['integration', 'resource_type'], name='scm_integra_integra_05db2f_idx'), models.Index(fields=['status'], name='scm_integra_status_4d23e1_idx'), models.Index(fields=['started_at'], name='scm_integra_started_1e72fa_idx')],
            },
        ),
    ]
