# Generated by Django 6.0.4 on 2026-05-31 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('import_type', models.CharField(choices=[('containers', 'Containers'), ('shipments', 'Shipments'), ('tracking_events', 'Tracking Events'), ('rates', 'Rates')], max_length=20, verbose_name='import type')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('validating', 'Validating'), ('validated', 'Validated'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20, verbose_name='status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='total rows')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='valid rows')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='invalid rows')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='processed rows')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='row number')),
                ('raw_data', models.JSONField(default=dict, verbose_name='raw data')),
                ('mapped_data', models.JSONField(default=dict, verbose_name='mapped data')),
                ('validated_data', models.JSONField(default=dict, verbose_name='validated data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('imported', 'Imported'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('errors', models.JSONField(default=list, verbose_name='errors')),
                ('imported_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='imported object ID')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='scm_imports.importjob', verbose_name='import job')),
                ('imported_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='imported content type')),
            ],
            options={
                'verbose_name': 'Import Row',
                'verbose_name_plural': 'Import Rows',
                'ordering': ['row_number'],
                'unique_together': {('import_job', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('message', models.TextField(verbose_name='message')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='field name')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=10, verbose_name='severity')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_errors', to='scm_imports.importjob', verbose_name='import job')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_errors', to='scm_imports.importrow', verbose_name='import row')),
            ],
            options={
                'verbose_name': 'Import Error',
                'verbose_name_plural': 'Import Errors',
                'ordering': ['severity', 'import_row__row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('import_type', models.CharField(choices=[('containers', 'Containers'), ('shipments', 'Shipments'), ('tracking_events', 'Tracking Events'), ('rates', 'Rates')], max_length=20, verbose_name='import type')),
                ('mapping', models.JSONField(default=dict, verbose_name='mapping')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to='teams.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Import Template',
                'verbose_name_plural': 'Import Templates',
            },
        ),
    ]
