# Generated by Django 6.0.4 on 2026-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_imports', '0003_alter_importjob_import_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='import_type',
            field=models.CharField(choices=[('containers', 'Containers'), ('container_movements', 'Container Movements'), ('purchase_orders', 'Purchase Orders'), ('shipments', 'Shipments'), ('tracking_events', 'Tracking Events'), ('rates', 'Rates'), ('bc_po_xlsx', 'Business Central Purchase Order XLSX')], max_length=20, verbose_name='import type'),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='import_type',
            field=models.CharField(choices=[('containers', 'Containers'), ('container_movements', 'Container Movements'), ('purchase_orders', 'Purchase Orders'), ('shipments', 'Shipments'), ('tracking_events', 'Tracking Events'), ('rates', 'Rates'), ('bc_po_xlsx', 'Business Central Purchase Order XLSX')], max_length=20, verbose_name='import type'),
        ),
    ]
