# Generated by Django 6.0.4 on 2026-06-01 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, verbose_name='External ID')),
                ('po_number', models.CharField(max_length=100, verbose_name='PO Number')),
                ('supplier_no', models.CharField(max_length=100, verbose_name='Supplier No')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('status', models.CharField(choices=[('open', 'Open'), ('released', 'Released'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('closed', 'Closed')], default='open', max_length=30, verbose_name='Status')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order Date')),
                ('expected_receipt_date', models.DateField(blank=True, null=True, verbose_name='Expected Receipt Date')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Currency')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', 'po_number'],
                'unique_together': {('team', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('PARTIALLY_SHIPPED', 'Partially Shipped'), ('FULLY_SHIPPED', 'Fully Shipped'), ('LOADED', 'Loaded'), ('ARRIVED', 'Arrived'), ('RECEIVED', 'Received')], max_length=30, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scm_procurement.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Purchase Order Event',
                'verbose_name_plural': 'Purchase Order Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, verbose_name='External ID')),
                ('line_no', models.CharField(max_length=20, verbose_name='Line No')),
                ('item_no', models.CharField(max_length=100, verbose_name='Item No')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('ordered_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Ordered Qty')),
                ('shipped_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Shipped Qty')),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Received Qty')),
                ('expected_receipt_date', models.DateField(blank=True, null=True, verbose_name='Expected Receipt Date')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm_procurement.purchaseorder', verbose_name='Purchase Order')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Purchase Order Line',
                'verbose_name_plural': 'Purchase Order Lines',
                'ordering': ['line_no'],
                'unique_together': {('purchase_order', 'external_id')},
            },
        ),
    ]
