# Generated by Django 6.0.4 on 2026-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_procurement', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['team', 'status'], name='scm_procure_team_id_c9aacc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['team', '-order_date'], name='scm_procure_team_id_8624f6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['team', 'supplier_no'], name='scm_procure_team_id_ff643e_idx'),
        ),
    ]
