# Generated by Django 6.0.4 on 2026-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_procurement', '0002_purchaseorder_scm_procure_team_id_c9aacc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Unit Price'),
        ),
    ]
