# Generated by Django 6.0.4 on 2026-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_procurement', '0003_add_unit_price_to_purchase_order_line'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last synced at'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw payload'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_active',
            field=models.BooleanField(default=True, verbose_name='Source active'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_company_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source company ID'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Source deleted at'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_last_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Source last modified at'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_system',
            field=models.CharField(choices=[('business_central', 'Business Central'), ('document_import', 'Document import'), ('manual', 'Manual')], default='business_central', max_length=30, verbose_name='Source system'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sync_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sync hash'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last synced at'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw payload'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_active',
            field=models.BooleanField(default=True, verbose_name='Source active'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Source deleted at'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_last_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Source last modified at'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='sync_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sync hash'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['team', 'source_system'], name='scm_procure_team_id_097f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['team', 'source_active'], name='scm_procure_team_id_9b96ba_idx'),
        ),
    ]
