# Generated by Django 6.0.4 on 2026-09-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm_containers', '0012_container_tracking_provider_override'),
        ('scm_procurement', '0005_classify_manual_purchase_orders'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition', to='scm_containers.container', verbose_name='Container')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired_containers', to='scm_procurement.purchaseorderline', verbose_name='Purchase Order Line')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Acquired Container',
                'verbose_name_plural': 'Acquired Containers',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['team', 'purchase_order_line'], name='scm_procure_team_id_33661a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContainerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='How much of the line went into this container. Leave blank when it is not known.', max_digits=12, null=True, verbose_name='Quantity')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='scm_containers.container', verbose_name='Container')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_loads', to='scm_procurement.purchaseorderline', verbose_name='Purchase Order Line')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Container Load',
                'verbose_name_plural': 'Container Loads',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['team', 'purchase_order_line'], name='scm_procure_team_id_1f443b_idx'), models.Index(fields=['team', 'container'], name='scm_procure_team_id_becfcc_idx')],
                'constraints': [models.UniqueConstraint(fields=('purchase_order_line', 'container'), name='unique_container_load_per_po_line')],
            },
        ),
    ]
