/* tslint:disable */
/* eslint-disable */
/**
 * Container Orchistration Layer
 * Container Supply Chain Layer is an operational platform built for container trading, depot operations, and inbound logistics management.  The system connects procurement, shipment tracking, inventory, landed cost, reservation management, and dispatch planning into one unified operational layer. It provides real-time visibility into what containers are ordered, in transit, available, reserved, and ready for delivery.  Designed to integrate with ERP systems, depot systems, and shipping line tracki
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `hr` - Human Resources
 * * `finance` - Finance
 * * `engineering` - Engineering
 * * `marketing` - Marketing
 * * `sales` - Sales
 * @export
 */
export const DepartmentEnum = {
    Hr: 'hr',
    Finance: 'finance',
    Engineering: 'engineering',
    Marketing: 'marketing',
    Sales: 'sales'
} as const;
export type DepartmentEnum = typeof DepartmentEnum[keyof typeof DepartmentEnum];


export function instanceOfDepartmentEnum(value: any): boolean {
    for (const key in DepartmentEnum) {
        if (Object.prototype.hasOwnProperty.call(DepartmentEnum, key)) {
            if (DepartmentEnum[key as keyof typeof DepartmentEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DepartmentEnumFromJSON(json: any): DepartmentEnum {
    return DepartmentEnumFromJSONTyped(json, false);
}

export function DepartmentEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentEnum {
    return json as DepartmentEnum;
}

export function DepartmentEnumToJSON(value?: DepartmentEnum | null): any {
    return value as any;
}

export function DepartmentEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DepartmentEnum {
    return value as DepartmentEnum;
}

