/* tslint:disable */
/* eslint-disable */
/**
 * Container Orchistration Layer
 * Container Supply Chain Layer is an operational platform built for container trading, depot operations, and inbound logistics management.  The system connects procurement, shipment tracking, inventory, landed cost, reservation management, and dispatch planning into one unified operational layer. It provides real-time visibility into what containers are ordered, in transit, available, reserved, and ready for delivery.  Designed to integrate with ERP systems, depot systems, and shipping line tracki
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenInvitation } from './OpenInvitation';
import {
    OpenInvitationFromJSON,
    OpenInvitationFromJSONTyped,
    OpenInvitationToJSON,
    OpenInvitationToJSONTyped,
} from './OpenInvitation';

/**
 * 
 * @export
 * @interface UserInvitationsResponse
 */
export interface UserInvitationsResponse {
    /**
     * 
     * @type {Array<OpenInvitation>}
     * @memberof UserInvitationsResponse
     */
    results: Array<OpenInvitation>;
}

/**
 * Check if a given object implements the UserInvitationsResponse interface.
 */
export function instanceOfUserInvitationsResponse(value: object): value is UserInvitationsResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function UserInvitationsResponseFromJSON(json: any): UserInvitationsResponse {
    return UserInvitationsResponseFromJSONTyped(json, false);
}

export function UserInvitationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInvitationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(OpenInvitationFromJSON)),
    };
}

  export function UserInvitationsResponseToJSON(json: any): UserInvitationsResponse {
      return UserInvitationsResponseToJSONTyped(json, false);
  }

  export function UserInvitationsResponseToJSONTyped(value?: UserInvitationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(OpenInvitationToJSON)),
    };
}

